sonar.projectKey=EP05P2F5_citasalud-f5-backend
sonar.organization=ep05p2f51

# Configuración de JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/DTO/**,**/entities/**,**/*Application.java,**/*Config.java,**/mapper/**,**/exception/**,**/config/DataInitializer.java
sonar.coverage.inclusions=**/service/**,**/controller/**,**/config/Jwt*,**/repository/**

# Excluir archivos que no son código
sonar.exclusions=**/target/**,**/.mvn/**,**/*.xml,**/*.yml,**/*.yaml,**/*.properties

# Incluir solo código fuente
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Configuración de calidad
sonar.java.source=17
sonar.sourceEncoding=UTF-8