spring.application.name=Feature5PQRS
# ===============================
# CONFIGURACION DE DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.koxfpqfykxclxhzmwqdp
spring.datasource.password=4kurs7uNDBgiFsks
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración del pool de conexiones para Supabase
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
# ===============================
# CONFIGURACION JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.name=admin
spring.security.user.password=admin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
